# Generated by Django 6.1 on 2026-08-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your Resume/CV (PDF recommended)', null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
